### ISSUE TITLE
Gitlab synchronization is broken?

### ISSUE THREAD

**Issue by manikmagar** [jbake-org/jbake.org#155]
Although the site code is hosted here in Github, the site is published after mirroring this repo on https://gitlab.com/jbake-org/jbake.org and running the gitlab CI pipeline. 

Looks like the subscription model has changed on Gitlab which broke this repository mirroring - https://about.gitlab.com/pricing/faq-efficient-free-tier/#public-projects-on-gitlab-saas-free-tier

![image](https://user-images.githubusercontent.com/877286/228976327-5656fcf6-9fdb-4f89-b2e3-a9ae057701fc.png)

The site may not have been built since 2022-07-01. 

@jonbullock The pages could be moved back to hosting on GitHub Pages. I think it was moved to Gitlab for SSL support in 2017, but now Github Pages [has it too](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site).

**Comment by jonbullock** [comment]
Yeah I think moving back to GitHub Pages is the best option going forward, keeps everything together and makes it simpler in terms of infrastructure.
