### ISSUE TITLE
Update documentation: List separatror for  asciidoctor.attributes appears to be comma, not spaces.

### ISSUE THREAD

**Issue by mgfeller** [jbake-org/jbake.org#38]
Looks like the separator for the option asciidoctor.attributes is a comma, not spaces.

Suggestion for documentation change (8.1.31. Default Asciidoctor attributes):

_The value for this configuration option is a comma separated list of key-value pairs. The default value defines Prettify as the source highlighter to be used._

**Comment by jonbullock** [comment]
Thanks for raising this issue, you are correct.
