### ISSUE TITLE
Simple installation steps on home page

### ISSUE THREAD

**Issue by manikmagar** [jbake-org/jbake.org#65]
Home Page should highlight the quick steps to install and build sites with jbake. Something like below -
 
```
curl -s "https://get.sdkman.io" | bash
sdk install jbake
mkdir awesome-jbake && cd awesome-jbake
jbake -i
jbake -b -s
```

Head to the browser and visit http://localhost:8820 to see your new site.

**Comment by jonbullock** [comment]
Great idea.
