### ISSUE TITLE
Incorrect Exception class is used in "9.2. API".

### ISSUE THREAD

**Issue by shalugin** [jbake-org/jbake.org#72]
http://jbake.org/docs/2.5.1/#api

Should be "Exception" instead of "JBakeException".

**Comment by jonbullock** [comment]
The code does throw a JBakeException: https://github.com/jbake-org/jbake/blob/v2.5.1/src/main/java/org/jbake/app/Oven.java#L75

**Comment by jonbullock** [comment]
Relates to #73

**Comment by shalugin** [comment]
> The code does throw a JBakeException: https://github.com/jbake-org/jbake/blob/v2.5.1/src/main/java/org/jbake/app/Oven.java#L75

@jonbullock, see https://github.com/jbake-org/jbake/blob/v2.5.1/src/main/java/org/jbake/app/Oven.java#L47

**Comment by jonbullock** [comment]
Ahh thanks for pointing that out, that is to cover if a ConfigurationException is thrown while trying load the configuration. I'll update the example code to catch both scenarios and explain why each may occur.
