### ISSUE TITLE
Move site hosting over to GitLab pages

### ISSUE THREAD

**Issue by jonbullock** [jbake-org/jbake.org#87]
Needs doing before #76

**Comment by manikmagar** [comment]
I have -

1. Created jbake-org group on Gitlab
2. Imported jbake.org from Github to Gitlab
3. Enabled gitlab-ci to build pages on jbake.org
4. Current site is available at - https://jbake-org.gitlab.io/jbake.org/. Resource paths are broken as it is being served in sub-folder.
5. Added Team in the group.

Next -
1. Point jbake.org to Gitlab pages.
2. Configure Cloudflare to server jbake.org over HTTPS (see #76 )

**Comment by jonbullock** [comment]
- [x] Pointed jbake.org at GitLab pages
- [x] Setup Cloudflare for jbake.org
